name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    # Weekly: Wednesday 7:00am PST (15:00 UTC).
    - cron: "0 15 * * 3"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    name: Apple platforms
    runs-on: macos-26
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.4.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}-macos
          repository-cache: true
      - run: xcrun swift --version
      - run: bazel build //Sources/AsyncAlgorithmsExample:tvos_build_test || true
      - run: find $(bazel info output_base)/execroot -name "InternalCollectionsUtilities.swiftmodule-0.params" -print -exec cat {} \;
      - run: bazel test //...

  macos-explicit-modules:
    name: Apple platforms (explicit modules)
    runs-on: macos-26
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.4.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}-macos-explicit-modules
          repository-cache: true
      - run: bazel test --config=explicit-modules //...

  linux:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2.4.0
        with:
          swift-version: "6.2"
      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}-linux
          repository-cache: true
      - run: which swiftc
      - run: swiftc --version
      - run: bazel test //...

  # linux-explicit-modules:
  #   name: Linux (explicit modules)
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: swift-actions/setup-swift@v2.4.0
  #       with:
  #         swift-version: "6.2"
  #     - uses: bazel-contrib/setup-bazel@0.19.0
  #       with:
  #         bazelisk-cache: true
  #         disk-cache: ${{ github.workflow }}-linux-explicit-modules
  #         repository-cache: true
  #     - run: which swiftc
  #     - run: swiftc --version
  #     - run: bazel test --config=explicit-modules //...
